export const tableData = {
  header: [
    {
      contents: [
        { content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { content: '%', rowSpanNumber: 2 },
        { content: 'Gols', rowSpanNumber: 2 }
      ]
    },
    {
      contents: [
        { content: 'H' },
        { content: '01' },
        { content: '04' },
        { content: '07' },
        { content: '10' },
        { content: '13' },
        { content: '16' },
        { content: '19' },
        { content: '22' },
        { content: '25' },
        { content: '28' },
        { content: '31' },
        { content: '34' },
        { content: '37' },
        { content: '40' },
        { content: '43' },
        { content: '46' },
        { content: '49' },
        { content: '52' },
        { content: '55' },
        { content: '58' }
      ]
    }
  ],
  body: [
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Blue' },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Green' },
        { content: '01', colorType: 'Red' },
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01' },
        { content: '01' }
      ]
    },
    {
      contents: [
        { content: '01', isCheckBox: true },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01', colorType: 'Red' },
        { content: '01' },
        { content: '01' }
      ]
    }
  ],
  footer: [
    {
      contents: [
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' },
        { title: '4', content: '33%' }
      ]
    }
  ]
}
