import { SideEffect } from '@/components/dashboard'
import { TNavigationProps } from '@/components/dashboard/SideEffect'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app'
}

const navigationData: TNavigationProps[] = [
  { text: 'Dashboard', icon: 'home', url: '/' },
  { text: 'Ranking', icon: 'trophy', url: '/ranking' },
  { text: 'Assinaturas', icon: 'recurrences', url: '/' },
  { text: 'Robôs', icon: 'robot', url: '/robots' },
  { text: 'Espião', icon: 'spy', url: '/spy' },
  { text: 'Últimos jogos', icon: 'last_games', url: '/lastGames' },
  { text: 'Integração telegram', icon: 'telegram', url: '/telegramIntegration' },
  { text: 'Tipster', icon: 'tipster', url: '/tipster' },
  { text: 'Estatísticas', icon: 'chart', url: '/analysis' }
]

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex w-full h-screen">
      <SideEffect data={navigationData} />
      <div className="flex-1 w-full p-500 space-y-500 overflow-y-auto">{children}</div>
    </div>
  )
}
