import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Page',
  description: 'Generated by create next app'
}

export default function pageLayout({ children }: { children: React.ReactNode }) {
  return <div className="flex w-full h-screen">{children}</div>
}
