export * from './types'
export { default as Heading01 } from './Heading01'
export { default as Heading01s } from './Heading01s'
export { default as Heading02 } from './Heading02'
export { default as Heading02s } from './Heading02s'
export { default as Heading03 } from './Heading03'
export { default as Heading03s } from './Heading03s'
export { default as Heading04 } from './Heading04'
export { default as Heading04s } from './Heading04s'
export { default as Heading05 } from './Heading05'
export { default as Heading05s } from './Heading05s'
export { default as Heading06 } from './Heading06'
export { default as Heading06ss } from './Heading06s'
export { default as Paragraph01 } from './Paragraph01'
export { default as Paragraph02 } from './Paragraph02'
export { default as Paragraph03 } from './Paragraph03'
export { default as Caption } from './Caption'
