export const tableData = {
  body: [
    {
      contents: [
        { content: '10', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '9', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '8', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '7', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '6', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '5', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '4', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '3', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '2', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    },
    {
      contents: [
        { content: '1', isBorder: false },
        { content: '1' },
        { content: '2' },
        { content: '3' },
        { content: '4' },
        { content: '5' },
        { content: '6' },
        { content: '7' },
        { content: '8' },
        { content: '9' },
        { content: '10' },
        { content: '11' },
        { content: '12' },
        { content: '13' },
        { content: '14' },
        { content: '15' },
        { content: '16' },
        { content: '17' },
        { content: '18' },
        { content: '19' },
        { content: '20' }
      ]
    }
  ]
}
